library(ggplot2)
library(extrafont)
library(gridExtra)

font_import()
loadfonts(device="win")       
fonts() 

load("classical.RData") ## load the data generated by Ser_classical.R and classical.R

p_seq=c(1,5,10,50,100,200)

plot_list <- list() 
 
for(i in 1:(length(p_seq)-1)){
p=NULL
p=p_seq[i]

df1=NULL
df1<-data.frame(
  R1=(1-pchisq(true_null[i,1,],p)), R2=(1-pchisq(true_null[i,2,],p)),
  R3=(1-pchisq(true_null[i,3,],p))
)
plot_list[[i]] <- ggplot(df1)+
        stat_density(aes(x=R1, colour="LRT"), bw=0.01, lwd=1, geom="line", position="identity")+
        stat_density(aes(x=R3, colour="Score"), bw=0.01, lwd=1, geom="line", position="identity")+
        stat_density(aes(x=R2, colour="Wald"), bw=0.01, lwd=1, geom="line", position="identity")+
        scale_color_manual(values=c("LRT"="#009E73", "Score"="#0072B2","Wald"=  "#D55E00"),
                           labels = c("LRT","Score","Wald"), name="test")+
        xlim(0,1)+ylim(0,2.5)+
        xlab(paste0("p=", p)) + ylab("Density")+
        theme(text=element_text(family="Times New Roman", face="bold", size=15), legend.position ="right")  
}

i=length(p_seq)

p=NULL
p=p_seq[i]

df1=NULL
df1<-data.frame(
    R1=(1-pchisq(true_null[i,1,],p)), R2=(1-pchisq(true_null[i,2,],p)),
    R3=(1-pchisq(true_null[i,3,],p))
)
plot_list[[i]] <- ggplot(df1)+
    stat_density(aes(x=R1, colour="LRT"), bw=0.01, lwd=1, geom="line", position="identity")+
    stat_density(aes(x=R3, colour="Score"), bw=0.01, lwd=1, geom="line", position="identity")+
    stat_density(aes(x=R2, colour="Wald"), bw=0.01, lwd=1, geom="line", position="identity")+
    scale_color_manual(values=c("LRT"="#009E73", "Score"="#0072B2","Wald"=  "#D55E00"),
                      labels = c("LRT","Score","Wald"), name="test")+
    xlim(0,1)+ 
    xlab(paste0("p=", p)) + ylab("Density")+
    theme(text=element_text(family="Times New Roman", face="bold", size=15), legend.position ="right")  

p1=grid.arrange(grobs=plot_list,ncol=2)
p1

 